name: Check README Workflow

on: [push, workflow_dispatch] # workflow_dispatch додає кнопку ручного запуску (крок 6)

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Hello World
        run: echo "Hello World! Checking files..."
        
      - name: Check if README.md exists
        run: |
          if [ -f README.md ]; then
            echo "Success: README.md is there!"
          else
            echo "Error: README.md is missing!"
            exit 1
          fi
